### ISSUE TITLE
jinja2 TemplateNotFound report.html

### ISSUE THREAD

**Issue by kilodalton** [joshuaavalon/file_hash#1]
After installing v1.0.1 via PyPI, `file_hash -h` and any command returns this error:
>jinja2.exceptions.TemplateNotFound: report.html

As in:
>>>Traceback (most recent call last):
  File "_[local_Python_path]_/bin/file_hash", line 7, in <module>
    from file_hash.__main__ import main
  File "_[local_Python_packages_path]_/file_hash/__main__.py", line 7, in <module>
    from file_hash.func import generate_hash, validate_hash
  File "_[local_Python_packages_path]_/file_hash/func.py", line 10, in <module>
    from file_hash.report import Report
  File "_[local_Python_packages_path]_/file_hash/report.py", line 13, in <module>
    template = environment.get_template("report.html")
  File "_[local_Python_packages_path]_/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "_[local_Python_packages_path]_/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "_[local_Python_packages_path]_/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "_[local_Python_packages_path]_/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: report.html

**Comment by kilodalton** [comment]
It looks like the `templates` directory isn't part of the PyPI download. Copying it into the right location fixes the error/error message.
